{
  config,
  lib,
  pkgs,
  inputs,
  modulesPath,
  ...
}:
let
  # Niri output configuration
  niriOutputs = {
    "DP-1" = {
      mode = "3440x1440@144.000";
      scale = 1.0;
      variableRefreshRate = true;
    };
  };

  # Ghostty terminal settings
  ghosttySettings = {
    fontSize = 12;
    backgroundOpacity = 0.95;
    backgroundBlurRadius = 32;
  };

  # Generate raw KDL for outputs
  outputsKdl = lib.concatStringsSep "\n\n" (
    lib.mapAttrsToList (
      name: value:
      let
        modeStr = lib.optionalString (value.mode != null) "  mode \"${value.mode}\"\n";
        vrrStr = lib.optionalString value.variableRefreshRate "  variable-refresh-rate\n";
        scaleStr = lib.optionalString (value.scale != null) "  scale ${toString value.scale}\n";
      in
      "output \"${name}\" {\n${modeStr}${vrrStr}${scaleStr}}"
    ) niriOutputs
  );
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./disko.nix
    ../default.nix
  ];

  boot = {
    kernelParams = [
      "pcie_aspm=force"
      "consoleblank=60"
      "acpi_enforce_resources=lax"
    ];
    kernelModules = [
      "kvm-amd"
      "zenpower"
    ];
    extraModulePackages = [ config.boot.kernelPackages.zenpower ];
    blacklistedKernelModules = [ "k10temp" ];
    loader = {
      timeout = 0;
      efi.canTouchEfiVariables = true;
      systemd-boot.enable = true;
    };
    kernelPackages = pkgs.linuxPackages_zen;
  };

  networking = {
    hostName = "lilith";
    networkmanager = {
      enable = true;
      wifi.powersave = false;
      dns = "systemd-resolved";
    };
    nameservers = [
      "192.168.0.2"
      "9.9.9.9"
    ];
  };

  services.resolved = {
    enable = true;
    dnssec = "allow-downgrade";
    domains = [ "~." ];
    fallbackDns = [ "9.9.9.9" ];
    extraConfig = ''
      DNSOverTLS=opportunistic
    '';
  };

  hardware = {
    enableRedistributableFirmware = true;
    bluetooth.enable = true;
    cpu.amd = {
      updateMicrocode = true;
      ryzen-smu.enable = true;
    };
    graphics = {
      enable = true;
      enable32Bit = true;
    };
    amdgpu.opencl.enable = true;
  };

  modules.virtualization.enable = true;

  services.power-profiles-daemon.enable = true;

  users.users.zekurio.extraGroups = [ "networkmanager" ];

  # Desktop environment configuration (merged from modules/desktop)
  security.polkit.enable = true;
  services.gnome.gnome-keyring.enable = true;
  services.dbus.enable = true;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  security.pam.services.greetd.text = ''
    auth substack login
    account include login
    password substack login
    session include login
  '';

  environment.sessionVariables = {
    NIXOS_OZONE_WL = "1";
    SSH_AUTH_SOCK = "/home/zekurio/.bitwarden-ssh-agent.sock";
    XCURSOR_THEME = "graphite-dark";
    XCURSOR_SIZE = "24";
    GTK_ICON_THEME_NAME = "Papirus-Dark";
    XDG_CURRENT_DESKTOP = "niri";
    QT_QPA_PLATFORM = "wayland";
    ELECTRON_OZONE_PLATFORM_HINT = "auto";
    QT_QPA_PLATFORMTHEME = "gtk3";
    QT_QPA_PLATFORMTHEME_QT6 = "gtk3";
  };

  environment.systemPackages = with pkgs; [
    papirus-icon-theme
    graphite-cursors
    adw-gtk3
    glib
    gtk3
    gtk4
    libsForQt5.qt5ct
    qt6Packages.qt6ct
    lact
  ];

  systemd.packages = with pkgs; [ lact ];
  systemd.services.lactd.wantedBy = [ "multi-user.target" ];

  systemd.tmpfiles.rules =
    let
      rocmEnv = pkgs.symlinkJoin {
        name = "rocm-combined";
        paths = with pkgs.rocmPackages; [
          rocblas
          hipblas
          clr
        ];
      };
    in
    [
      "L+    /opt/rocm   -    -    -     -    ${rocmEnv}"
    ];

  programs.niri.enable = true;

  programs.dms-shell = {
    enable = true;
    quickshell.package = inputs.quickshell.packages.${pkgs.stdenv.hostPlatform.system}.quickshell;
    systemd = {
      enable = true;
      restartIfChanged = true;
    };
    enableSystemMonitoring = true;
    enableClipboard = true;
    enableVPN = true;
    enableDynamicTheming = true;
    enableAudioWavelength = true;
    enableCalendarEvents = true;
  };

  programs.dsearch = {
    enable = true;
    systemd.enable = true;
  };

  services.displayManager.dms-greeter = {
    enable = true;
    compositor.name = "niri";
    configHome = "/home/zekurio";
  };

  home-manager.users.zekurio = {
    xdg.configFile."niri/config.kdl".text = ''
      // Generated by NixOS configuration
      config-notification {
          disable-failed
      }

      // Output configuration
      ${outputsKdl}

      gestures {
          hot-corners {
              off
          }
      }

      input {
          keyboard {
              xkb {
                  layout "us"
              }
              numlock
          }
          touchpad {
          }
          mouse {
          }
          trackpoint {
          }
      }

      layout {
          background-color "transparent"
          center-focused-column "never"
          preset-column-widths {
              proportion 0.33333
              proportion 0.5
              proportion 0.66667
          }
          default-column-width { proportion 0.5; }
          border {
              off
              width 4
              active-color   "#707070"
              inactive-color "#d0d0d0"
              urgent-color   "#cc4444"
          }
          shadow {
              softness 30
              spread 5
              offset x=0 y=5
              color "#0007"
          }
          struts {
          }
      }

      layer-rule {
          match namespace="^quickshell$"
          place-within-backdrop true
      }

      overview {
          workspace-shadow {
              off
          }
      }

      spawn-at-startup "bash" "-c" "wl-paste --watch cliphist store &"

      environment {
          XDG_CURRENT_DESKTOP "niri"
          QT_QPA_PLATFORM "wayland"
          ELECTRON_OZONE_PLATFORM_HINT "auto"
          QT_QPA_PLATFORMTHEME "gtk3"
          QT_QPA_PLATFORMTHEME_QT6 "gtk3"
      }

      hotkey-overlay {
          skip-at-startup
      }

      prefer-no-csd
      screenshot-path "~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png"

      animations {
          workspace-switch {
              spring damping-ratio=0.80 stiffness=523 epsilon=0.0001
          }
          window-open {
              duration-ms 150
              curve "ease-out-expo"
          }
          window-close {
              duration-ms 150
              curve "ease-out-quad"
          }
          horizontal-view-movement {
              spring damping-ratio=0.85 stiffness=423 epsilon=0.0001
          }
          window-movement {
              spring damping-ratio=0.75 stiffness=323 epsilon=0.0001
          }
          window-resize {
              spring damping-ratio=0.85 stiffness=423 epsilon=0.0001
          }
          config-notification-open-close {
              spring damping-ratio=0.65 stiffness=923 epsilon=0.001
          }
          screenshot-ui-open {
              duration-ms 200
              curve "ease-out-quad"
          }
          overview-open-close {
              spring damping-ratio=0.85 stiffness=800 epsilon=0.0001
          }
      }

      // Window rules
      window-rule {
          match app-id=r#"^org\.wezfurlong\.wezterm$"#
          default-column-width {}
      }
      window-rule {
          match app-id=r#"^org\.gnome\."#
          draw-border-with-background false
          geometry-corner-radius 12
          clip-to-geometry true
      }
      window-rule {
          match app-id=r#"^gnome-control-center$"#
          match app-id=r#"^pavucontrol$"#
          match app-id=r#"^nm-connection-editor$"#
          default-column-width { proportion 0.5; }
          open-floating false
      }
      window-rule {
          match app-id=r#"^gnome-calculator$"#
          match app-id=r#"^galculator$"#
          match app-id=r#"^blueman-manager$"#
          match app-id=r#"^org\.gnome\.Nautilus$"#
          match app-id=r#"^steam$"#
          match app-id=r#"^xdg-desktop-portal$"#
          open-floating true
      }
      window-rule {
          match app-id=r#"^org\.wezfurlong\.wezterm$"#
          match app-id="Alacritty"
          match app-id="zen"
          match app-id="com.mitchellh.ghostty"
          match app-id="kitty"
          draw-border-with-background false
      }
      window-rule {
          match is-active=false
          opacity 0.9
      }
      window-rule {
          match app-id=r#"firefox$"# title="^Picture-in-Picture$"
          match app-id="zoom"
          open-floating true
      }
      window-rule {
          match app-id=r#"org.quickshell$"#
          open-floating true
      }

      debug {
          honor-xdg-activation-with-invalid-serial
      }

      recent-windows {
          binds {
              Alt+Tab         { next-window scope="output"; }
              Alt+Shift+Tab   { previous-window scope="output"; }
              Alt+grave       { next-window filter="app-id"; }
              Alt+Shift+grave { previous-window filter="app-id"; }
          }
      }

      // Include DMS files
      include "dms/colors.kdl"
      include "dms/layout.kdl"
      include "dms/alttab.kdl"
      include "dms/binds.kdl"
    '';

    programs.ghostty = {
      enable = true;
      enableZshIntegration = true;
      settings = lib.mkMerge [
        {
          font-size = ghosttySettings.fontSize;
          window-decoration = false;
          window-padding-x = 12;
          window-padding-y = 12;
          background-opacity = ghosttySettings.backgroundOpacity;
          background-blur-radius = ghosttySettings.backgroundBlurRadius;
          cursor-style = "block";
          cursor-style-blink = true;
          scrollback-limit = 3023;
          mouse-hide-while-typing = true;
          copy-on-select = false;
          confirm-close-surface = false;
          app-notifications = "no-clipboard-copy,no-config-reload";
          keybind = [
            "ctrl+shift+n=new_window"
            "ctrl+t=new_tab"
            "ctrl+plus=increase_font_size:1"
            "ctrl+minus=decrease_font_size:1"
            "ctrl+zero=reset_font_size"
            "shift+enter=text:\\n"
          ];
          unfocused-split-opacity = 0.7;
          unfocused-split-fill = "#44464f";
          gtk-titlebar = false;
          gtk-single-instance = true;
          shell-integration = "detect";
          shell-integration-features = "cursor,sudo,title,no-cursor";
          config-file = [ "config-dankcolors" ];
        }
      ];
    };

    fonts.fontconfig.enable = true;

    home.sessionVariables = {
      GTK_ICON_THEME_NAME = "Papirus-Dark";
      XCURSOR_THEME = "graphite-dark";
      XCURSOR_SIZE = "24";
    };

    xdg.portal = {
      enable = true;
      extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
      config.common.default = "*";
    };

    home.packages = with pkgs; [
      (nerd-fonts.symbols-only)
      inter
      fira-code
      noto-fonts
      noto-fonts-cjk-sans
      noto-fonts-color-emoji
      font-awesome
      brave
      zed-editor
      vesktop
      bitwarden-desktop
      bitwarden-cli
      deezer-enhanced
      jellyfin-desktop
      xwayland-satellite
      wl-clipboard
      cliphist
    ];
  };

  time.timeZone = "Europe/Vienna";
  system.autoUpgrade = {
    enable = true;
    allowReboot = true;
    dates = "Sun 04:00";
    flake = "github:zekurio/nix#lilith";
  };

  # DO NOT TOUCH THIS
  system.stateVersion = "25.11";
}
