{ pkgs, ... }:
{
  imports = [ ./dms/default.nix ];

  # Use niri from nixpkgs (25.11)
  programs.niri.enable = true;

  environment.sessionVariables.NIXOS_OZONE_WL = "1";
  environment.systemPackages = [ pkgs.xwayland-satellite ];

  # Write niri config with environment variables and DMS includes
  home-manager.users.zekurio.xdg.configFile."niri/config.kdl".text = ''
    // Environment variables for Qt theming
    environment {
      QT_QPA_PLATFORMTHEME "gtk3"
      QT_QPA_PLATFORMTHEME_QT6 "gtk3"
    }

    // DMS dynamic configuration includes
    // These files are generated by DMS at runtime in ~/.config/niri/dms/
    include "dms/colors.kdl"
    include "dms/layout.kdl"
    include "dms/alttab.kdl"
    include "dms/binds.kdl"
  '';
}
