name: Build Tabris Tarball

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@v12

            - name: Setup Nix cache
              uses: DeterminateSystems/magic-nix-cache-action@v7

            - name: Build tarball
              run: nix build .#nixosConfigurations.tabris.config.system.build.tarballBuilder

            - name: Prepare artifact
              run: |
                  mkdir -p artifacts
                  cp result/tarball/*.tar.xz artifacts/ 2>/dev/null || cp result/*.tar.xz artifacts/ 2>/dev/null || true
                  ls -lh artifacts/

            - name: Upload tarball artifact
              uses: actions/upload-artifact@v4
              with:
                  name: tabris-tarball
                  path: artifacts/
                  retention-days: 30

            - name: Create release on tag
              if: startsWith(github.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v1
              with:
                  files: artifacts/*.tar.xz
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
