name: Release tabris WSL tarball
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31

      - name: Build tabris tarball
        run: |
          nix_bin=$(which nix)
          sudo $nix_bin run .#nixosConfigurations.tabris.config.system.build.tarballBuilder

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: tabris.wsl
          path: nixos.wsl

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            nixos.wsl
